[profile.default]
solc_version = "0.8.19"
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "solmate/=lib/solmate/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]
via_ir = true
optimizer = true
optimizer_runs = 200
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
